workflows:
  ios-build:
    name: Hydration Tracker iOS Build
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: "Codemagic Build Key"
    environment:
      flutter: stable
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.matthewabel.hydrationTracker
    scripts:
      - name: Get Flutter Packages
        script: flutter pub get
      - name: Build and Sign iOS App
        script: flutter build ipa --release
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true