workflows:
  ios-build:
    name: Hydration Tracker iOS Build
    instance_type: mac_mini_m2
    environment:
      flutter: stable
    scripts:
      - name: Get Flutter Packages
        script: flutter pub get
      - name: Build iOS for Simulator
        script: flutter build ios --simulator
      - name: Zip for Appetize
        script: |
          cd build/ios/iphonesimulator
          zip -r Runner.app.zip Runner.app
    artifacts:
      - build/ios/iphonesimulator/Runner.app.zip